name: ModernTeleport
version: '1.3'
main: org.modernTeleport.ModernTeleport
api-version: '1.21'
authors: [ Lin ]
description: 简单而现代化的传送相关指令插件
commands:
  tpa:
    description: tpa指令，用于玩家之间的传送请求
    usage: ""
  tpr:
    description: tpr指令，用于随机传送
    usage: ""
    aliases: [rtp]
  tpahelp:
    description: tpa指令教程
  hub:
    description: 返回主城
    usage: ""
